# 운영 환경

server:
  port: 8020

# db 환경

spring:
  h2:
    console:
      enabled: true
      path: /h2

# db 접속 정보 (default)

jpa:
    database: H2
datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver